server:
  port: 8081
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinebookshop?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
     template_update_delay: 0
     classic_compatible: true
     number_format: 0.######
     template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zlw.onlinebookshop.entity
